# Generated by Django 4.2.5 on 2023-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250)),
                ('order_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('order_desc', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=2)),
            ],
        ),
    ]
