# Generated by Django 4.2.5 on 2023-10-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_card_number_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
